export const Margin = {
    BOTTOM_SMALL: 'margin-bottom--small',
    BOTTOM_MEDIUM: 'margin-bottom--medium',
    BOTTOM_LARGE: 'margin-bottom--large',
    TOP_SMALL: 'margin-top--large',
    TOP_MEDIUM: 'margin-top--large',
    TOP_LARGE: 'margin-top--large',
    LEFT_SMALL: 'margin-left--large',
    LEFT_MEDIUM: 'margin-left--large',
    LEFT_LARGE: 'margin-left--large',
    RIGHT_SMALL: 'margin-right--large',
    RIGHT_MEDIUM: 'margin-right--large',
    RIGHT_LARGE: 'margin-right--large',
    AROUND_SMALL: 'margin-around--large',
    AROUND_MEDIUM: 'margin-around--large',
    AROUND_LARGE: 'margin-around--large',
    VERTICAL_SMALL: 'margin-vertical--large',
    VERTICAL_MEDIUM: 'margin-vertical--large',
    VERTICAL_LARGE: 'margin-vertical--large',
    HORIZONTAL_SMALL: 'margin-horizontal--large',
    HORIZONTAL_MEDIUM: 'margin-horizontal--large',
    HORIZONTAL_LARGE: 'margin-horizontal--large',
};