export const Padding = {
    BOTTOM_SMALL: 'padding-bottom--small',
    BOTTOM_MEDIUM: 'padding-bottom--medium',
    BOTTOM_LARGE: 'padding-bottom--large',
    TOP_SMALL: 'padding-top--large',
    TOP_MEDIUM: 'padding-top--large',
    TOP_LARGE: 'padding-top--large',
    LEFT_SMALL: 'padding-left--large',
    LEFT_MEDIUM: 'padding-left--large',
    LEFT_LARGE: 'padding-left--large',
    RIGHT_SMALL: 'padding-right--large',
    RIGHT_MEDIUM: 'padding-right--large',
    RIGHT_LARGE: 'padding-right--large',
    AROUND_SMALL: 'padding-around--large',
    AROUND_MEDIUM: 'padding-around--large',
    AROUND_LARGE: 'padding-around--large',
    VERTICAL_SMALL: 'padding-vertical--large',
    VERTICAL_MEDIUM: 'padding-vertical--large',
    VERTICAL_LARGE: 'padding-vertical--large',
    HORIZONTAL_SMALL: 'padding-horizontal--large',
    HORIZONTAL_MEDIUM: 'padding-horizontal--large',
    HORIZONTAL_LARGE: 'padding-horizontal--large',
};